pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4 Shield/Terminate'
            }
        }
        stage('Wait for Reboot') {
            steps {
                sleep time: 6, unit: 'MINUTES'
            }
        }
        stage('Build & Start') {
            steps {
                build job: 'P4 Shield/build'
            }
        }
    }
}

