pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4 Shield - olive/terminate'
            }
        }
        stage('Start') {
            steps {
                build job: 'P4 Shield - olive/start'
            }
        }
    }
}

