pipeline {
    agent any

    stages {
        stage('[User] Latency'){
//             steps{
//                 sh '''
//                 ssh ksl-iwai.ksl.ci.kyutech.ac.jp << EOF

//                 echo "[TCP]"
//                 echo "netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
//                 netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
//                 sleep 10

//                 echo "[UDP]"
//                 echo "netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
//                 netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
//                 sleep 10

//                 echo "[TCP]"
//                 echo "netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m xxx"
//                 echo "1460, 65477"
//                 netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1460
//                 sleep 30
//                 netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 65477
//                 sleep 30

//                 echo "[UDP]"
//                 echo "netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m xxx"
//                 echo "1472, 65489"
//                 netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
//                 sleep 30
//                 netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 65489


// EOF
//                 '''
//             }
            steps{
                sh '''
                ssh ksl-iwai.ksl.ci.kyutech.ac.jp << EOF

                echo "[TCP]"
                echo "netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
                netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
                sleep 10

                echo "[UDP]"
                echo "netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
                netperf -t omni -H olive-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
                sleep 10

                echo "[TCP]"
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1460
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1460
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1460
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 65477
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 65477
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 65477

                echo "[UDP]"
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 65489
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 65489
                netperf -H olive-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 65489
EOF
                '''
            }
        }
    }
}

