pipeline {
    agent any

    stages {
        stage('[olive] Update scripts repository') {
            steps{
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                cd p4-ubpf_scripts
                git pull
EOF
                '''
            }
        }
        stage('[olive] Start ivshmem-server') {
            steps{
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                ./p4-ubpf_scripts/ovs/ivshmem-start.sh
EOF
                '''
            }
        }
        stage('[olive] Start P4 VM') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp <<EOF
                if virsh domstate p4 | grep -q running; then
                    echo "P4 VM is already running."
                else
                    echo "Starting P4 VM..."
                    virsh start p4
                fi
EOF
                '''
                sleep time: 30, unit: 'SECONDS'
            }
        }
        stage('[p4] Update scripts repository') {
            steps{
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local ' << InnerEOF
                cd p4-ubpf_scripts
                git pull
InnerEOF
                '
EOF
                '''
            }
        }
        stage('[p4] Prepare ivshmem'){
            steps{
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local '
                sudo su << InnerEOF
                cd p4-ubpf_scripts/p4
                ./shm.sh || true
InnerEOF
                '
EOF
                '''
            }
        }
        stage('[p4] Run uBPF Runtime'){
            steps{
                JENKINS_NODE_COOKIE=dontKillMe sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local '
                sudo su << InnerEOF
                nohup p4u &
InnerEOF
                '
EOF
                '''
            }
        }
        stage('[olive] Run OVS') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-ctl stop || true
                sleep 3
                ovs-ctl start
EOF
                '
                '''
                sleep time: 5, unit: 'SECONDS'
            }
        }
        stage('[olive] Turn off kernel data_path') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                iptables -A INPUT -i enp3s0f1 -j DROP
                iptables -A FORWARD -i enp3s0f1 -j DROP
EOF
                '
                '''
            }
        }
        stage('[olive] Turn on Userspace TCP Segmentation Offload') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-vsctl set Open_vSwitch . other_config:userspace-tso-enable=true
EOF
                '
                '''
            }
        }
        stage('[olive] Start User VM') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp <<EOF
                if virsh domstate user | grep -q running; then
                    echo "User VM is already running."
                else
                    echo "Starting User VM..."
                    virsh start user
                fi
EOF
                '''
                sleep time: 30, unit: 'SECONDS'
            }
        }
        stage('[User] Prepare ivshmem'){
            steps{
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no olive-vm1.ksl.ci.kyutech.ac.jp '
                sudo su << InnerEOF
                cd p4-ubpf_scripts
                git pull
                cd user
                ./shm.sh || true
InnerEOF
                '
EOF
                '''
            }
        }
        stage('Check status') {
            steps {
                build job: 'P4 Shield - olive/check network'
            }
        }
    }
}

