pipeline {
    agent any

    stages {
        stage('[sub9] Update scripts repository') {
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                cd p4-ubpf_scripts
                git pull
EOF
                '''
            }
        }
        stage('[sub9] Start ivshmem-server') {
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                ./p4-ubpf_scripts/ovs/ivshmem-start.sh
EOF
                '''
            }
        }
        stage('[sub9] Start P4 VM') {
            steps {
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp <<EOF
                if virsh domstate p4 | grep -q running; then
                    echo "P4 VM is already running."
                else
                    echo "Starting P4 VM..."
                    virsh start p4
                    for i in {1..30}; do
                        if virsh domstate p4 | grep -q running; then
                            echo "P4 VM is now running."
                            break
                        fi
                        sleep 1
                    done
                    if ! virsh domstate p4 | grep -q running; then
                        echo "Error: P4 VM did not start within expected time."
                        exit 1
                    fi
                fi
EOF
                '''
            }
        }
        stage('[p4] Update scripts repository') {
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local ' << InnerEOF
                cd p4-ubpf_scripts
                git pull
InnerEOF
                '
EOF
                '''
            }
        }
        stage('[p4] Prepare ivshmem'){
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local '
                sudo su << InnerEOF
                cd p4-ubpf_scripts/p4
                ./shm.sh || true
InnerEOF
                '
EOF
                '''
            }
        }
        stage('[p4] Run uBPF Runtime'){
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no p4.local '
                sudo ./p4-ubpf_scripts/p4/p4-ctl.sh p4u
                '
EOF
                '''
            }
        }
        stage('[sub9] Run OVS') {
            steps {
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-ctl stop || true
                sleep 3
                ovs-ctl start
EOF
                '
                '''
                sleep time: 5, unit: 'SECONDS'
            }
        }
        stage('[sub9] Turn off kernel data_path') {
            steps {
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                iptables -A INPUT -i eno12409np1 -j DROP
                iptables -A FORWARD -i eno12409np1 -j DROP
EOF
                '
                '''
            }
        }
        stage('[sub9] Turn on Userspace TCP Segmentation Offload') {
            steps {
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-vsctl set Open_vSwitch . other_config:userspace-tso-enable=true
EOF
                '
                '''
            }
        }
        stage('[sub9] Start User VM') {
            steps {
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp <<EOF
                if virsh domstate user | grep -q running; then
                    echo "User VM is already running."
                else
                    echo "Starting User VM..."
                    virsh start user
                    for i in {1..30}; do
                        if virsh domstate user | grep -q running; then
                            echo "User VM is now running."
                            break
                        fi
                        sleep 1
                    done
                    if ! virsh domstate user | grep -q running; then
                        echo "Error: User VM did not start within expected time."
                        exit 1
                    fi
                fi
EOF
                '''
            }
        }
        stage('[User] Prepare ivshmem'){
            steps{
                sh '''
                ssh sub9.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no sub9-vm1.ksl.ci.kyutech.ac.jp '
                sudo su << InnerEOF
                cd p4-ubpf_scripts
                git pull
                cd user
                ./shm.sh || true
InnerEOF
                '
EOF
                '''
            }
        }
        stage('Check status') {
            steps {
                build job: 'P4 Shield - sub9/check network'
            }
        }
    }
}

