pipeline {
    agent any
    stages {
        stage('loop') {
            steps {
                script {
                    for (i in 1..5) {
                        build job: 'P4Shield - sub9/measure'
                    }
                }
            }
        }
    }
}
