pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4Shield - cloud-2-sev-user/terminate'
            }
        }
        stage('Start') {
            steps {
                build job: 'P4Shield - cloud-2-sev-user/start'
            }
        }
    }
}

