pipeline {
    agent any

    stages {
        stage('[sub7] Switch datapath_type to netdev') {
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-vsctl set bridge ovsbr0 datapath_type=netdev
EOF
                '
                '''
                sleep time: 5, unit: 'SECONDS'
            }
        }
    }
}

