pipeline {
    agent any

    stages {
        stage('Shutdown VMs') {
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp <<EOF
                virsh shutdown user
                virsh shutdown p4
                while virsh list --state-running | grep -q user; do
                  sleep 1
                done
                while virsh list --state-running | grep -q p4; do
                  sleep 1
                done
EOF
                '''
            }
        }
        stage('[sub7] Stop OVS') {
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-ctl stop
EOF
                '
                '''
            }
        }
        stage('[sub7] Stop ivshmem-server'){
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp '
                sudo su<< EOF
                kill $(pgrep ivshmem-server)
                rm /dev/shm/ivshmem 2> /dev/null
                rm /tmp/ivshmem_socket 2> /dev/null
EOF
                '
                '''
            }
        }
    }
}

