pipeline {
    agent any

    stages {
        stage('[sub7] Shutdown VMs') {
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp <<EOF
                virsh shutdown user
                while virsh list --state-running | grep -q user; do
                  sleep 1
                done
EOF
                '''
            }
        }
        stage('[sub7] Stop OVS') {
            steps {
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-ctl stop
EOF
                '
                '''
            }
        }
        stage('Build & Start') {
            steps {
                build job: 'P4 Shield/build'
            }
        }
    }
}

