pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4 Shield/terminate'
            }
        }
        stage('Build & Start') {
            steps {
                build job: 'P4 Shield/build'
            }
        }
    }
}

