pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4Shield - cloud-2-sev-p4/terminate'
            }
        }
        stage('Build & Start') {
            steps {
                build job: 'P4Shield - cloud-2-sev-p4/build'
            }
        }
    }
}

