pipeline {
    agent any

    stages {
        stage('[User] tcp'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF
                ssh -o StrictHostKeyChecking=no sub7-vm1.ksl.ci.kyutech.ac.jp '
                sudo su << InnerEOF
                iperf3 -c peach.ksl.ci.kyutech.ac.jp
                InnerEOF
                '
                EOF
                '''
            }
        }
    }
}

