pipeline {
    agent any

    stages {
        stage('[User] Latency'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF

                echo "[TCP]"
                echo "netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
                netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY

                echo "[UDP]"
                echo "netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY"
                netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
EOF
                '''
            }
        }
        stage('[User] Throughput'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF

                echo "[TCP]"
                echo "netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM"
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM

                echo "[UDP]"
                echo "netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472"
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
EOF
                '''
            }
        }
        stage('[User] Throughput - Detail'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF

                echo "[TCP]"
                echo "netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 6, 70, 198, 454, 966, 1222, 1460"
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 6
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 70
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 198
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 454
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 966
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1222
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t TCP_STREAM -- -m 1460

                echo "[UDP]"
                echo "netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 18, 82, 210, 466, 978, 1234, 1472"
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 18
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 82
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 210
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 466
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 978
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1234
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
EOF
                '''
            }
        }
    }
}

