pipeline {
    agent any

    stages {
        stage('[User] Latency'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF

                echo "[TCP]"
                netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T TCP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY

                echo "[UDP]"
                netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
EOF
                '''
            }
        }
        stage('[User] Throughput'){
            steps{
                sh '''
                ssh sub7.ksl.ci.kyutech.ac.jp << EOF

                SERVER_IP="sub7-vm1.ksl.ci.kyutech.ac.jp"
                RUNS=5
                DURATION=10

                TEST_TYPE="TCP_STREAM" # テストタイプ (TCP_STREAM / UDP_STREAM / TCP_RR / UDP_RR)
                echo "${TEST_TYPE}"
                results=()
                for i in $(seq 1 $RUNS); do
                    result=$(netperf -H $SERVER_IP -t $TEST_TYPE -l $DURATION | tail -1 | awk '{print $NF}')
                    results+=($result)
                done

                total=0
                for value in "${results[@]}"; do
                    total=$(echo "$total + $value" | bc)
                done
                average=$(echo "scale=2; $total / $RUNS" | bc)

                echo "測定結果: ${results[@]}"
                echo "平均: $average Mbps"


                echo "[UDP]"
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472
                netperf -H sub7-vm1.ksl.ci.kyutech.ac.jp -t UDP_STREAM -- -m 1472

                netperf -t omni -H sub7-vm1.ksl.ci.kyutech.ac.jp -- -d rr -T UDP -k MIN_LATENCY,MEAN_LATENCY,P90_LATENCY,P99_LATENCY,MAX_LATENCY,STDDEV_LATENCY
EOF
                '''
            }
        }
    }
}

