pipeline {
    agent any

    stages {
        stage('[olive] Switch datapath_type to netdev') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-vsctl set bridge ovsbr1 datapath_type=netdev
EOF
                '
                '''
                sleep time: 5, unit: 'SECONDS'
            }
        }
        stage('[olive] Turn off kernel data_path') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                iptables -A INPUT -i enp3s0f1 -j DROP
                iptables -A FORWARD -i enp3s0f1 -j DROP
EOF
                '
                '''
            }
        }
        stage('[olive] Turn on Userspace TCP Segmentation Offload') {
            steps {
                sh '''
                ssh olive.ksl.ci.kyutech.ac.jp '
                sudo su <<EOF
                export PATH=$PATH:/usr/local/share/openvswitch/scripts/
                ovs-vsctl set Open_vSwitch . other_config:userspace-tso-enable=true
EOF
                '
                '''
            }
        }
    }
}

