pipeline {
    agent any

    stages {
        stage('Terminate') {
            steps {
                build job: 'P4Shield - sub9/terminate'
            }
        }
        stage('Build & Start') {
            steps {
                build job: 'P4Shield - sub9/build'
            }
        }
    }
}

